trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_USERNAME: $(DOCKER_USERNAME)  # DockerHub username stored in Variables section
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)  # DockerHub password stored as secret

stages:
  - stage: BuildDocker
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Docker Build and Push'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
                
          # Push Docker image to Docker Hub
          - task: Docker@2
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'push'
              tags: |
                latest
                $(Build.BuildId)

  # Trivy scan stage depends on BuildDocker stage completion
  - stage: ScanImage
    displayName: 'Scan Docker Image with Trivy'
    dependsOn: 
      - BuildDocker  # Ensure BuildDocker stage is completed first
    jobs:
      - job: Scan
        displayName: 'Run Trivy Image Scan'
        steps:
          # Log in to Docker Hub and pull the image for scanning
          - script: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker pull $(DOCKER_USERNAME)/chancetek_devops
            displayName: 'Login to Docker and Pull Image'

          # Install Trivy for scanning
          - script: |
              sudo apt-get update
              sudo apt-get install -y wget
              wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.41.0_Linux-64bit.deb
              sudo dpkg -i trivy_0.41.0_Linux-64bit.deb
            displayName: 'Install Trivy'

          # Run Trivy scan
          - script: |
              trivy image $(DOCKER_USERNAME)/chancetek_devops
            displayName: 'Docker Scan with Trivy'

  # TestApp stage depends on ScanImage stage completion
  - stage: TestApp
    displayName: 'Run Selenium Tests'
    dependsOn: 
      - ScanImage  # Ensure ScanImage stage is completed first
    jobs:
      - job: Test
        displayName: 'Run Selenium Tests'
        steps:
          - script: |
              # Command to start the app or run Selenium tests
              python -m pytest tests/
            displayName: 'Run Selenium Tests'


