trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'



stages:
  - stage: BuildDocker
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Docker Build and Push'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
          - task: Docker@2
            displayName: 'Log in to DockerHub'
            inputs:
              containerRegistry: 'DockerHubRegistry'
              command: 'login'
          - script: |
              echo "Docker build started" > /home/vsts/work/_temp/task_outputs/build_output.txt
              docker build -t $(DOCKER_USERNAME)/chancetek_devops .
              docker push $(DOCKER_USERNAME)/chancetek_devops
              echo "Docker build and push completed" >> /home/vsts/work/_temp/task_outputs/build_output.txt
            displayName: 'Docker Build and Push'

  
  - stage: TestApp
    displayName: 'Run Selenium Tests'
    
    jobs:
      - job: Test
        displayName: 'Run Selenium Tests'
        steps:
          - checkout: self
          - script: |
              ls -R
            displayName: 'List workspace contents'
          - script: |
              pip install pytest
            displayName: 'Install pytest'
          - script: |
              mkdir -p /home/vsts/work/_temp/task_outputs
              python -m pytest tests/ > /home/vsts/work/_temp/task_outputs/test_output.txt
            displayName: 'Run Selenium tests'


  - stage: PushImage
    displayName: 'Push Docker Image to DockerHub'
    
    jobs:
      - job: Push
        displayName: 'Push Docker Image'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'push'
              tags: 'latest'
          - script: |
              echo "Docker image push completed" > /home/vsts/work/_temp/task_outputs/push_output.txt
            displayName: 'Log Docker Push Completion'

