trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent to run the pipeline

variables:
  dockerRegistryServiceConnection: 'DockerHubRegistry'  # Name of your Docker Hub service connection
  imageRepository: '$(dockerusername)/chancetek_devops'  # Your Docker Hub repo (username/repository)
  dockerfilePath: '**/Dockerfile'  # Path to your Dockerfile
  tag: 'latest'  # Docker image tag

steps:
# Step 1: Checkout the code from the repository
- task: Checkout@1
  displayName: 'Checkout code'

# Step 2: Log in to Docker Hub using the service connection
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: 'login'
    containerRegistry: $(dockerRegistryServiceConnection)  # Use the service connection variable

# Step 3: Build the Docker image
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    containerRegistry: $(dockerRegistryServiceConnection)  # Use the service connection variable
    repository: $(imageRepository)  # Reference the image repository (username/repo)
    Dockerfile: $(dockerfilePath)  # Use the Dockerfile path
    tags: |
      $(tag)  # Use 'latest' as the image tag

# Step 4: Push the Docker image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: 'push'
    containerRegistry: $(dockerRegistryServiceConnection)  # Use the service connection variable
    repository: $(imageRepository)  # Reference the image repository (username/repo)
    tags: |
      $(tag)  # Use 'latest' as the image tag

