trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: BuildDocker
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Docker Build and Push'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
                
          # Push Docker image to Docker Hub
          - task: Docker@2
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              containerRegistry: 'DockerHubRegistry'
              repository: '$(DOCKER_USERNAME)/chancetek_devops'
              command: 'push'
              tags: |
                latest
                $(Build.BuildId)

  - stage: ScanImage
    displayName: 'Scan Docker Image with Trivy'
    dependsOn: 
      - BuildDocker  # Ensure BuildDocker stage is completed first
    jobs:
      - job: Scan
        displayName: 'Run Trivy Image Scan'
        steps:
          # Log in to Docker Hub and pull the image for scanning
          - script: |
              echo "Logging in to Docker Hub..."
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker pull $(DOCKER_USERNAME)/chancetek_devops
            displayName: 'Login to Docker and Pull Image'
            continueOnError: false  # Fail if login or pull fails

          # Install Trivy for scanning
          - script: |
              echo "Installing Trivy..."
              sudo apt-get update
              sudo apt-get install -y wget
              wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.41.0_Linux-64bit.deb
              sudo dpkg -i trivy_0.41.0_Linux-64bit.deb
              trivy --version  # Output the version of Trivy to confirm installation
            displayName: 'Install Trivy'

          # Run Trivy scan
          - script: |
              echo "Running Trivy scan..."
              trivy image $(DOCKER_USERNAME)/chancetek_devops
            displayName: 'Docker Scan with Trivy'
            continueOnError: false  # Fail if Trivy scan fails



